# Generated by Django 5.2.7 on 2025-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singingclass',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
