# Generated by Django 5.2.7 on 2025-11-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_seats',
            field=models.PositiveIntegerField(default=0, help_text='Seats remaining for bookings.'),
        ),
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.PositiveIntegerField(default=0, help_text='Total seats for this event.'),
        ),
    ]
