# Generated by Django 5.2.7 on 2025-11-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_singingclass_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='api_event_date_58da15_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='api_event_locatio_469e25_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basic ticket price (₹).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('live', 'Live'), ('karaoke', 'Karaoke')], default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Premium ticket price (₹).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VIP ticket price (₹).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=1.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy general ticket price (optional).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
