# Generated by Django 5.2.7 on 2025-11-25 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_show_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photographybooking',
            options={},
        ),
        migrations.RemoveField(
            model_name='photographybooking',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='photographybooking',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='photographybooking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='photographybooking',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='photographybooking',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='photographybooking',
            name='videographers_count',
        ),
        migrations.AddField(
            model_name='photographybooking',
            name='addon_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photographybooking',
            name='addon_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='photographybooking',
            name='event_type_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photographybooking',
            name='package_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='photographybooking',
            name='payment_methods_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='photographybooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photographybooking',
            name='client',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photographybooking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='photographybooking',
            name='duration_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='photographybooking',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photographybooking',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photographybooking',
            name='package_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photographybooking',
            name='photographers_count',
            field=models.IntegerField(default=1),
        ),
    ]
