# Generated by Django 5.2.7 on 2025-11-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_available_seats_event_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='basic_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for Basic tickets (optional).', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='premium_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for Premium tickets (optional).', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='vip_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for VIP tickets (optional).', null=True),
        ),
    ]
