# Generated by Django 5.2.7 on 2025-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_basic_seats_event_premium_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='basic_seats',
            field=models.PositiveIntegerField(default=0, help_text='Seats available in Basic tier.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='premium_seats',
            field=models.PositiveIntegerField(default=0, help_text='Seats available in Premium tier.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_seats',
            field=models.PositiveIntegerField(default=0, help_text='Seats available in VIP tier.'),
        ),
    ]
