# Generated by Django 5.2.7 on 2025-11-25 05:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_photographybooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videography',
            name='package_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Package price in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='videography',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videography_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videography',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Duration in hours (e.g. 1.50 = 1h 30m)', max_digits=5),
        ),
    ]
