# Generated by Django 5.2.7 on 2025-11-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_basic_seats_alter_event_premium_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='basic_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for Basic tickets (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='premium_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for Premium tickets (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Seats allocated for VIP tickets (optional).', null=True),
        ),
    ]
