# Generated by Django 5.2.7 on 2025-11-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_basic_seats_alter_event_premium_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='seat_numbers',
            field=models.JSONField(blank=True, default=list, help_text="List of seat ids for this booking (e.g. ['vip-1-01','vip-1-02'])."),
        ),
    ]
