# Generated by Django 5.2.7 on 2025-11-07 09:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videography',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='videography',
            name='api_videogr_deliver_498d4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='videography',
            name='api_videogr_editor_147cd8_idx',
        ),
        migrations.RenameField(
            model_name='videography',
            old_name='delivery_date',
            new_name='shoot_date',
        ),
        migrations.RemoveField(
            model_name='videography',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='videography',
            name='remarks',
        ),
        migrations.AddField(
            model_name='videography',
            name='client_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='videography',
            name='duration_hours',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Duration in hours, e.g., 2 or 1.5', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videography',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='videography',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='videography',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='videography',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videography',
            name='package_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Deluxe', 'Deluxe')], default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='videography',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='videography',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videography',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videography',
            name='editor',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='videography',
            name='project',
            field=models.CharField(max_length=150),
        ),
    ]
