# Generated by Django 5.2.7 on 2025-11-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiomaster',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='studiomaster',
            name='api_studiom_name_a4791c_idx',
        ),
        migrations.RemoveIndex(
            model_name='studiomaster',
            name='api_studiom_is_acti_b0a1de_idx',
        ),
    ]
