# Generated by Django 5.2.7 on 2025-10-30 06:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='api_event_date_58da15_idx'), models.Index(fields=['location'], name='api_event_locatio_469e25_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('method', models.CharField(choices=[('Card', 'Credit/Debit Card'), ('UPI', 'UPI'), ('NetBanking', 'Net Banking'), ('Cash', 'Cash')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='api_payment_date_c7981c_idx'), models.Index(fields=['method'], name='api_payment_method_204434_idx')],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='api_show_date_16749e_idx'), models.Index(fields=['location'], name='api_show_locatio_1c0b17_idx')],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('studio_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=1, help_text='Duration in hours', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('payment_methods', models.CharField(blank=True, help_text='Comma-separated: Card, UPI, NetBanking', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Studio Booking',
                'verbose_name_plural': 'Studio Bookings',
                'ordering': ['-date', '-time_slot'],
                'indexes': [models.Index(fields=['date', 'time_slot'], name='api_studio_date_643fc7_idx'), models.Index(fields=['studio_name'], name='api_studio_studio__27094e_idx')],
                'constraints': [models.UniqueConstraint(fields=('studio_name', 'date', 'time_slot'), name='uniq_studio_date_timeslot')],
            },
        ),
        migrations.CreateModel(
            name='Videography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=2, help_text='Hours', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('editor', models.CharField(max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Videography Project',
                'verbose_name_plural': 'Videography Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['delivery_date'], name='api_videogr_deliver_498d4f_idx'), models.Index(fields=['editor'], name='api_videogr_editor_147cd8_idx')],
            },
        ),
    ]
