# Generated by Django 5.2.7 on 2025-10-31 10:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_payment_show_studio_videography'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('Private Booking', 'Private Booking'), ('Studio Rental', 'Studio Rental'), ('Equipment Rental', 'Equipment Rental'), ('Event/Show', 'Event/Show'), ('Singer Management', 'Singer Management'), ('Videography', 'Videography'), ('Sound System', 'Sound System'), ('Photography', 'Photography')], default='Private Booking', max_length=40)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('guests', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='private_bookings/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Private Booking',
                'verbose_name_plural': 'Private Bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', 'event_date'], name='api_private_created_bbfcb6_idx'), models.Index(fields=['status'], name='api_private_status_82824a_idx')],
            },
        ),
    ]
