# Generated by Django 5.2.7 on 2025-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studiomaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studiomaster',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='studiomaster',
            index=models.Index(fields=['name'], name='api_studiom_name_a4791c_idx'),
        ),
        migrations.AddIndex(
            model_name='studiomaster',
            index=models.Index(fields=['is_active'], name='api_studiom_is_acti_b0a1de_idx'),
        ),
    ]
