# Generated by Django 5.2.7 on 2025-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_studiomaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiomaster',
            name='area',
            field=models.CharField(blank=True, help_text='Area / locality (e.g., Andheri East)', max_length=160),
        ),
        migrations.AddField(
            model_name='studiomaster',
            name='city',
            field=models.CharField(blank=True, help_text='City (e.g., Mumbai)', max_length=120),
        ),
        migrations.AddField(
            model_name='studiomaster',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Optional Google Maps URL', max_length=500),
        ),
        migrations.AddField(
            model_name='studiomaster',
            name='size_sq_ft',
            field=models.CharField(blank=True, help_text='Studio size in square feet (e.g., 1200). Stored as text to allow flexible formats', max_length=40),
        ),
        migrations.AddField(
            model_name='studiomaster',
            name='state',
            field=models.CharField(blank=True, help_text='State (e.g., Maharashtra)', max_length=120),
        ),
        migrations.AlterField(
            model_name='studiomaster',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of people the studio can hold', null=True),
        ),
        migrations.AddIndex(
            model_name='studiomaster',
            index=models.Index(fields=['city'], name='api_studiom_city_15fb4d_idx'),
        ),
    ]
