# Generated by Django 5.2.7 on 2025-11-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_equipment_equipmentrental_delete_privatebooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('rented_by', models.CharField(blank=True, max_length=150)),
                ('rental_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Under Maintenance', 'Under Maintenance')], default='Available', max_length=32)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='api_equipme_name_7b7af3_idx'), models.Index(fields=['category'], name='api_equipme_categor_3e5015_idx'), models.Index(fields=['brand'], name='api_equipme_brand_83b2b2_idx'), models.Index(fields=['status'], name='api_equipme_status_437c22_idx')],
            },
        ),
    ]
