# Generated by Django 5.2.7 on 2025-11-15 10:52

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studiomaster_area_studiomaster_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.studio_image_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.studiomaster')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
                'indexes': [models.Index(fields=['studio'], name='api_studioi_studio__8c7aa2_idx'), models.Index(fields=['is_primary'], name='api_studioi_is_prim_63b5cc_idx')],
            },
        ),
    ]
