# Generated by Django 5.2.7 on 2025-11-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studioimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiomaster',
            name='size_sq_ft',
            field=models.CharField(blank=True, help_text='Studio size in square feet (e.g., 1200). Stored as text', max_length=40),
        ),
    ]
