# Generated by Django 5.2.7 on 2025-11-17 05:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studiomaster_size_sq_ft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=150)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Experience in years')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.models.singer_photo_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Singer',
                'verbose_name_plural': 'Singers',
                'ordering': ['-created_at'],
            },
        ),
    ]
