# Generated by Django 5.2.7 on 2025-11-17 06:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_singer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='singer',
            name='experience',
        ),
        migrations.AddField(
            model_name='singer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='singer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='singer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, optional +).', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AddField(
            model_name='singer',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
