# Generated by Django 5.2.7 on 2025-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_singer_options_remove_singer_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ('-id',), 'verbose_name': 'Singer', 'verbose_name_plural': 'Singers'},
        ),
        migrations.RemoveField(
            model_name='singer',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='singer',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singer',
            name='mobile',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='singer',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='genre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
