# Generated by Django 5.2.7 on 2025-11-17 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_singer_options_remove_singer_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingerRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(blank=True, max_length=200)),
                ('rental_start', models.DateTimeField()),
                ('rental_end', models.DateTimeField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_mobile', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.singer')),
            ],
            options={
                'ordering': ['-rental_start', '-created_at'],
            },
        ),
    ]
