# Generated by Django 5.2.7 on 2025-11-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_singer_options_alter_singer_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='education_in_music',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='favourite_singer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='reference_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='singer',
            name='special_achievement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
