# Generated by Django 5.2.7 on 2025-11-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_singer_options_remove_singer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
