# Generated by Django 5.2.7 on 2025-11-17 15:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_singer_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Singer', 'verbose_name_plural': 'Singers'},
        ),
        migrations.RenameField(
            model_name='singer',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='singer',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='education_in_music',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='favourite_singer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='singer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.singer_photo_upload_to),
        ),
        migrations.AlterField(
            model_name='singer',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='reference_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
