# Generated by Django 5.2.7 on 2025-11-17 16:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_singer_options_rename_active_singer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='singer',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='singer',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='education_in_music',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singer',
            name='favourite_singer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='singer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.singer_upload_to),
        ),
        migrations.AlterField(
            model_name='singer',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='singer',
            name='reference_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
