# Generated by Django 5.2.7 on 2025-11-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_singer_options_rename_is_active_singer_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='updated_at',
        ),
    ]
