# Generated by Django 5.2.7 on 2025-11-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_singer_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Singers'},
        ),
        migrations.RemoveField(
            model_name='singer',
            name='education_in_music',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='special_achievement',
        ),
        migrations.AddField(
            model_name='singer',
            name='achievement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='singer',
            name='education',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='singer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='area',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='singer',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='singer',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='favourite_singer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='singer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='singer',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='singer',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='singer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='singer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='singers/'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='singer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='reference_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='singer',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
