# Generated by Django 5.2.7 on 2025-11-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_singingclassadmission_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=20)),
                ('preferred_batch', models.CharField(choices=[('Morning (7:00 - 9:00)', 'Morning (7:00 - 9:00)'), ('Afternoon (1:00 - 3:00)', 'Afternoon (1:00 - 3:00)'), ('Evening (6:00 - 8:00)', 'Evening (6:00 - 8:00)')], max_length=50)),
                ('reference_by', models.CharField(blank=True, max_length=120, null=True)),
                ('agreed_terms', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SingingClassAdmission',
        ),
    ]
