# Generated by Django 5.2.7 on 2025-11-19 15:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0018_alter_singer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStudioBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(help_text='Customer full name', max_length=120)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('studio_name', models.CharField(blank=True, max_length=160)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(help_text='Start time in 24h, e.g. 09:00', max_length=10)),
                ('duration', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Duration in hours (e.g. 1.5)', max_digits=4)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total price for this booking', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studio', models.ForeignKey(help_text='Which studio is being booked', on_delete=django.db.models.deletion.PROTECT, related_name='user_bookings', to='api.studiomaster')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (if any) who created this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'time_slot'],
                'indexes': [models.Index(fields=['date'], name='User_Dashbo_date_5367ac_idx'), models.Index(fields=['studio'], name='User_Dashbo_studio__23ad47_idx'), models.Index(fields=['status'], name='User_Dashbo_status_74bbb2_idx')],
            },
        ),
    ]
