# Generated by Django 5.2.7 on 2025-11-20 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Dashboard', '0001_initial'),
        ('api', '0019_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstudiobooking',
            options={'ordering': ['-date', '-time_slot', '-created_at'], 'verbose_name': 'User studio booking', 'verbose_name_plural': 'User studio bookings'},
        ),
        migrations.RemoveIndex(
            model_name='userstudiobooking',
            name='User_Dashbo_date_5367ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='userstudiobooking',
            name='User_Dashbo_studio__23ad47_idx',
        ),
        migrations.RemoveIndex(
            model_name='userstudiobooking',
            name='User_Dashbo_status_74bbb2_idx',
        ),
        migrations.RemoveField(
            model_name='userstudiobooking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userstudiobooking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='userstudiobooking',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='userstudiobooking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='userstudiobooking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userstudiobooking',
            name='studio_name',
        ),
        migrations.AddField(
            model_name='userstudiobooking',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final agreed price (total, not per hour).', max_digits=10),
        ),
        migrations.AddField(
            model_name='userstudiobooking',
            name='customer_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudiobooking',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Duration in hours, e.g. 1.0, 1.5, 2.0', max_digits=4),
        ),
        migrations.AddField(
            model_name='userstudiobooking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userstudiobooking',
            name='payment_methods_csv',
            field=models.CharField(blank=True, help_text='Comma-separated payment methods.', max_length=200),
        ),
        migrations.AlterField(
            model_name='userstudiobooking',
            name='studio',
            field=models.ForeignKey(help_text='Studio being booked.', on_delete=django.db.models.deletion.PROTECT, related_name='user_bookings', to='api.studiomaster'),
        ),
        migrations.AlterField(
            model_name='userstudiobooking',
            name='time_slot',
            field=models.TimeField(help_text='Start time of the booking (24h).'),
        ),
        migrations.AlterField(
            model_name='userstudiobooking',
            name='user',
            field=models.ForeignKey(blank=True, help_text='If the customer is logged in, link the booking to the user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_studio_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
