# Generated by Django 5.2.7 on 2025-11-27 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1, help_text='Approximate duration in hours', max_digits=5)),
                ('location_venue', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('package_type', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Custom', 'Custom')], default='Standard', max_length=20)),
                ('num_photographers', models.IntegerField(default=1)),
                ('need_videography', models.BooleanField(default=False)),
                ('need_album', models.BooleanField(default=False)),
                ('need_drone', models.BooleanField(default=False)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_photography_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStudioBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField(help_text='Start time of the booking (24h).')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, help_text='Duration in hours, e.g. 1.0, 1.5, 2.0', max_digits=4)),
                ('payment_methods_csv', models.CharField(blank=True, help_text='Comma-separated payment methods.', max_length=200)),
                ('agreed_price', models.DecimalField(decimal_places=2, default=0, help_text='Final agreed price (total, not per hour).', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('studio', models.ForeignKey(help_text='Studio being booked.', on_delete=django.db.models.deletion.PROTECT, related_name='user_bookings', to='api.studiomaster')),
                ('user', models.ForeignKey(blank=True, help_text='If the customer is logged in, link the booking to the user account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_studio_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User studio booking',
                'verbose_name_plural': 'User studio bookings',
                'ordering': ['-date', '-time_slot', '-created_at'],
            },
        ),
    ]
